project:
  type: website

website:
  title: "Machine Learning Questions"
  navbar:
    background: primary
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "September 2022"
        contents:
          - 20220901.md
          - 20220902.md
          - 20220903.md
      - section: "August 2022"
        contents:
          - 20220817.md
          - 20220818.md
          - 20220819.md
          - 20220820.md
          - 20220821.md
          - 20220822.md
          - 20220823.md
          - 20220824.md
          - 20220825.md
          - 20220826.md
          - 20220827.md
          - 20220828.md
          - 20220829.md
          - 20220830.md
          - 20220831.md

format:
  html:
    theme:
      dark: darkly
      light: flatly
    toc: true
    css: styles.css



